### PR TITLE
app: rename to liteboot

### PR DESCRIPTION
**Pull request by rajkan01**
Rename LinaroCA reference to liteboot

Signed-off-by: Rajkumar Kanagaraj <rajkumar.kanagaraj@linaro.org>

### CODE REVIEW

**Comment by microbuilder** [comment]
@rajkan01 If we change the subject line in the certificates, we also need to make some code the to the Zephyr application, etc., which verify this value, or they will fail. That's the main reason I left those as is, but you did catch some other things I missed, thanks.

**Comment by microbuilder** [comment]
> @rajkan01 If we change the subject line in the certificates, we also need to make some code the to the Zephyr application, etc., which verify this value, or they will fail. That's the main reason I left those as is, but you did catch some other things I missed, thanks.

Do you mind removing the changes to `OrganizationalUnit` / `OU` for now, and we can come back to those when we're ready to make changes elswhere, and I can merge in the non `OU` fixes here today?

**Comment by rajkan01** [comment]
@microbuilder I removed the changes to OU for now and raised this issue https://github.com/Linaro/lite_bootstrap_server/issues/51 to fix that in future

**Review by microbuilder — APPROVED** [review]

**Comment by microbuilder** [comment]
Thanks for the fixes.

**Pull request merged**
